main/urls.py
from django.urls import path
from .views import (
    home, detail, posts, create_post, latest_posts,
    search_result,)

urlpatterns = [
    path("", home, name="home"),
    path("detail/<slug>/", detail, name="detail"),
    path("posts/<slug>/", posts, name="posts"),
    path("create_post", create_post, name="create_post"),
    path("latest_posts", latest_posts, name="latest_posts"),
    path("search", search_result, name="search_result"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('tinymce/', include('tinymce.urls')),
    path('account/', include('register.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

register/urls.py
from django.urls import path
from .views import signup, signin, update_profile, logout

urlpatterns = [
    path("signup/", signup, name="signup"),
    path("signin/", signin, name="signin"),
    path("update_profile/", update_profile, name="update_profile"),
    path("logout/", logout, name="logout"),
]

main/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django_resized import ResizedImageField
from tinymce.models import HTMLField
from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation
from taggit.managers import TaggableManager
from django.shortcuts import reverse


User = get_user_model()

class Author(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fullname = models.CharField(max_length=40, blank=True)
    slug = slug = models.SlugField(max_length=400, unique=True, blank=True, default="")
    bio = HTMLField(null=True, blank=True)
    points = models.IntegerField(default=0)
    profile_pic = ResizedImageField(size=[50, 80], quality=100, upload_to="authors", default="user.jpg", null=True, blank=True)

    def __str__(self):
        return self.user.username

    @property
    def num_posts(self):
        return Post.objects.filter(user=self).count()
    
    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.fullname)
            slug = base_slug
            counter = 1
            while Author.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = slug
        super(Author, self).save(*args, **kwargs)
    

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.fullname)
        super(Author, self).save(*args, **kwargs)

class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=400, unique=True, blank=True)
    description = models.TextField(default="description")

    class Meta:
        verbose_name_plural = "categories"
    def __str__(self):
        return self.title
    

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)

    def get_url(self):
        return reverse("posts", kwargs={
            "slug":self.slug
        })

    @property
    def num_posts(self):
        return Post.objects.filter(categories=self).count()
    
    @property
    def last_post(self):
        return Post.objects.filter(categories=self).latest("date")


class Reply(models.Model):
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content[:100]

    class Meta:
        verbose_name_plural = "replies"


class Comment(models.Model):
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    replies = models.ManyToManyField(Reply, blank=True)

    def __str__(self):
        return self.content[:100]


class Post(models.Model):
    title = models.CharField(max_length=400)
    slug = models.SlugField(max_length=400, unique=True, blank=True)
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    content = HTMLField()
    categories = models.ManyToManyField(Category)
    date = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
        related_query_name='hit_count_generic_relation'
    )
    tags = TaggableManager()
    comments = models.ManyToManyField(Comment, blank=True)
    closed = models.BooleanField(default=False)
    state = models.CharField(max_length=40, default="zero")
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse("detail", kwargs={
            "slug":self.slug
        })

    @property
    def num_comments(self):
        return self.comments.count()

    @property
    def last_reply(self):
        return self.comments.latest("date")

    

register/models.py
from django.db import models

# Create your models here.

register/forms.py
from django import forms
from main.models import Author

class UpdateForm(forms.ModelForm):
    
    class Meta:
        model = Author
        fields = ("fullname", "bio", "profile_pic")

register/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from register.forms import UpdateForm
from django.contrib.auth import logout as lt
from django.contrib import messages
from django.contrib.auth.models import User

#usernames = [user.username for user in User.objects.all()]

def signup(request):
    form = UserCreationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect("update_profile")
        else:
            form.add_error(None, "Invalid username or password")

    context = {
        "form": form,
        "title": "Signup",
    }
    return render(request, "register/signup.html", context)

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect

def signin(request):
    form = AuthenticationForm(request, data=request.POST)
    if request.method == "POST":
        if form.is_valid():
            user = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=user, password=password)
            if user is not None:
                login(request, user)
                return redirect("home")
            else:
                form.add_error(None, "Invalid username or password")  # Add custom error

    context = {
        "form": form,
        "title": "Signin",
    }
    return render(request, "register/signin.html", context)

@login_required
def update_profile(request):
    context = {}
    user = request.user 
    form = UpdateForm(request.POST, request.FILES)
    if request.method == "POST":
        if form.is_valid():
            update_profile = form.save(commit=False)
            update_profile.user = user
            update_profile.save()
            return redirect("home")

    context.update({
        "form": form,
        "title": "Update Profile",
    })
    return render(request, "register/update.html", context)

@login_required
def logout(request):
    lt(request)
    return redirect("home")

templates/register/signin.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <h1 style="text-align:center; margin-block:50px; font-size: 32px;">LogIn</h1>
  {% if form.non_field_errors %}
    <div class="error" style="text-align: center; font-size: larger;">
        {% for error in form.non_field_errors %}
            <pre style="color: red;">{{ error }}</pre>
        {% endfor %}
    </div>
{% endif %}
  <div style="display: flex; align-items: flex-end;">
    <form method="POST" action="." class="form-container" style="width: 50vw;">
      {% csrf_token %}
      <div id="div_id_username" class="form-group">
        <label for="id_username" class="label requiredField">Username<span class="asteriskField">*</span></label>
        <div>
          <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" class="input-field textinput textInput form-control is-invalid" required aria-invalid="true" id="id_username" />
          <p id="error_1_id_username" class="invalid-feedback helptext">
            <strong>This field is required.</strong>
          </p>
        </div>
      </div>
      <div id="div_id_password" class="form-group">
        <label for="id_password" class="label requiredField">Password<span class="asteriskField">*</span></label>
        <div>
          <input type="password" name="password" autocomplete="current-password" class="input-field textinput textInput form-control is-invalid" required aria-invalid="true" id="id_password" />
          <p id="error_1_id_password" class="invalid-feedback helptext">
            <strong>This field is required.</strong>
          </p>
        </div>
      </div>
      <input type="submit" value="Signin" class="submit-btn" style="margin-block:50px;" />
    </form>
  </div>
{% endblock %}

templates/register/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <h1 style="text-align:center; margin-block:50px; font-size: 32px;">Create An Account</h1>

  {% if form.non_field_errors %}
    <div class="error" style="text-align: center; font-size: larger;">
        {% for error in form.non_field_errors %}
            <pre style="color: red;">{{ error }}</pre>
        {% endfor %}
    </div>
{% endif %}

  <div style="display: flex; align-items: flex-end;">

  <form method="POST" action="." class="form-container" style="width: 50vw;">
    {% csrf_token %}

    <div id="div_id_username" class="form-group">
        <label for="id_username" class="label requiredField">
            Username<span class="asteriskField">*</span>
        </label>
        <div>
            <input 
                type="text" 
                name="username" 
                maxlength="150" 
                autocapitalize="none" 
                autocomplete="username" 
                autofocus 
                class="input-field textinput textInput form-control" 
                required 
                aria-describedby="id_username_helptext" 
                id="id_username" 
            />
        </div>
    </div>

    <div id="div_id_password1" class="form-group">
        <label for="id_password1" class="label">
            Password*
        </label>
        <div>
            <input 
                type="password" 
                name="password1" 
                autocomplete="new-password" 
                class="input-field textinput textInput form-control" 
                aria-describedby="id_password1_helptext" 
                id="id_password1" 
            />
        </div>
    </div>

    <div id="div_id_password2" class="form-group">
        <label for="id_password2" class="label">
            Password confirmation*
        </label>
        <div>
            <input 
                type="password" 
                name="password2" 
                autocomplete="new-password" 
                class="input-field textinput textInput form-control" 
                aria-describedby="id_password2_helptext" 
                id="id_password2" 
            />
        </div>
    </div>

    <div class="pass-policies">
        <pre style="color: whitesmoke;">Password must be alphanumerical and must contain at least 8 characters.</pre>
    </div>

    <input type="submit" value="Signup" class="submit-btn" style="margin-block:50px;" />
</form>
  </div>

{% endblock %}

templates/register/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<h1 style="text-align:center; margin-block:50px; font-size: 32px;">Hey {{user}}, Become An Author</h1>
<div style="display: flex; align-items: flex-end;">
    <form method="POST" action="." enctype="multipart/form-data" class="form-container" style="width: 50vw;">
        {% csrf_token %}
        
        <!-- Fullname Field -->
    <div id="div_id_fullname" class="form-group">
        <label for="id_fullname" class="label">
            Fullname
        </label>
        <div>
            <input 
                type="text" 
                name="fullname" 
                maxlength="40" 
                class="input-field textinput textInput form-control" 
                id="id_fullname" 
            />
        </div>
    </div>

    <!-- Bio Field -->
    <div id="div_id_bio" class="form-group">
        <label for="id_bio" class="label requiredField">
            Bio<span class="asteriskField">*</span>
        </label>
        <div>
            <textarea 
                aria-invalid="true" 
                class="input-field tinymce form-control is-invalid tinymce" 
                cols="40" 
                rows="10" 
                id="id_bio" 
                name="bio"
                data-mce-conf="{&quot;theme&quot;: &quot;silver&quot;, &quot;height&quot;: 500, &quot;menubar&quot;: false, &quot;browser_spellcheck&quot;: true, &quot;plugins&quot;: &quot;advlist,autolink,lists,link,image,charmap,preview,anchor,searchreplace,visualblocks,code,fullscreen,insertdatetime,media,table,help,wordcount&quot;, &quot;toolbar&quot;: &quot;undo redo | blocks | bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help&quot;, &quot;directionality&quot;: &quot;ltr&quot;, &quot;strict_loading_mode&quot;: 1, &quot;selector&quot;: &quot;#id_bio&quot;}"
                style="resize: none;"
            ></textarea>
            <p id="error_1_id_bio" class="invalid-feedback">
                <strong>This field is required.</strong>
            </p>
        </div>
    </div>

    <!-- Profile Picture Field -->
    <div id="div_id_profile_pic" class="form-group">
        <label for="id_profile_pic" class="label">
            Profile pic
        </label>
        <div>
            <input 
                type="file" 
                name="profile_pic" 
                accept="image/*" 
                class="form-control-file input-field" 
                id="id_profile_pic" 
            />
        </div>
    </div>

    <!-- Submit Button -->
    <input type="submit" value="Update" class="submit-btn" style="margin-block:50px;">
</form>
</div>

{% endblock content %}