main/urls.py
from django.urls import path
from .views import (
    home, detail, posts, create_post, latest_posts,
    search_result,)

urlpatterns = [
    path("", home, name="home"),
    path("detail/<slug>/", detail, name="detail"),
    path("posts/<slug>/", posts, name="posts"),
    path("create_post", create_post, name="create_post"),
    path("latest_posts", latest_posts, name="latest_posts"),
    path("search", search_result, name="search_result"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('tinymce/', include('tinymce.urls')),
    path('account/', include('register.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django_resized import ResizedImageField
from tinymce.models import HTMLField
from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation
from taggit.managers import TaggableManager
from django.shortcuts import reverse


User = get_user_model()

class Author(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fullname = models.CharField(max_length=40, blank=True)
    slug = slug = models.SlugField(max_length=400, unique=True, blank=True, default="")
    bio = HTMLField(null=True, blank=True)
    points = models.IntegerField(default=0)
    profile_pic = ResizedImageField(size=[50, 80], quality=100, upload_to="authors", default="user.jpg", null=True, blank=True)

    def __str__(self):
        return self.user.username

    @property
    def num_posts(self):
        return Post.objects.filter(user=self).count()
    
    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.fullname)
            slug = base_slug
            counter = 1
            while Author.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = slug
        super(Author, self).save(*args, **kwargs)
    

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.fullname)
        super(Author, self).save(*args, **kwargs)

class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=400, unique=True, blank=True)
    description = models.TextField(default="description")

    class Meta:
        verbose_name_plural = "categories"
    def __str__(self):
        return self.title
    

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)

    def get_url(self):
        return reverse("posts", kwargs={
            "slug":self.slug
        })

    @property
    def num_posts(self):
        return Post.objects.filter(categories=self).count()
    
    @property
    def last_post(self):
        return Post.objects.filter(categories=self).latest("date")


class Reply(models.Model):
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content[:100]

    class Meta:
        verbose_name_plural = "replies"


class Comment(models.Model):
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    replies = models.ManyToManyField(Reply, blank=True)

    def __str__(self):
        return self.content[:100]


class Post(models.Model):
    title = models.CharField(max_length=400)
    slug = models.SlugField(max_length=400, unique=True, blank=True)
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    content = HTMLField()
    categories = models.ManyToManyField(Category)
    date = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
        related_query_name='hit_count_generic_relation'
    )
    tags = TaggableManager()
    comments = models.ManyToManyField(Comment, blank=True)
    closed = models.BooleanField(default=False)
    state = models.CharField(max_length=40, default="zero")
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse("detail", kwargs={
            "slug":self.slug
        })

    @property
    def num_comments(self):
        return self.comments.count()

    @property
    def last_reply(self):
        return self.comments.latest("date")

    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:ital@1&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/notify.js/2.0.0/notify.min.js" integrity="sha512-iy8/ErLJUuqWbu30yUSCxXtE3FCDZi3y5op0Duqdp7vtpeh1E6ZyAPnRS+OrJHddh4uP30oYpwNt7TXPbmP5lQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>

<body>
    <header>
        <!--NavBar Section-->
        <div class="navbar">
            <nav class="navigation hide" id="navigation">
                <span class="close-icon" id="close-icon" onclick="showIconBar()"><i class="fa fa-close"></i></span>
                <ul class="nav-list">
                    <li class="nav-item"><a href="{% url 'home' %}">Home</a></li>
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li class="nav-item"><a href="{% url 'signup' %}">Signup</a></li>
                    <li class="nav-item"><a href="{% url 'signin' %}">Signin</a></li>
                    {% endif %}
                </ul>
            </nav>
            <a class="bar-icon" id="iconBar" onclick="hideIconBar()"><i class="fa fa-bars"></i></a>
            <div class="brand">LET'S Discuss</div>
            {% if user.is_authenticated %}
            <div style="font-size:50px;font-weight300px;margin-left:100px;"><a href="{% url 'create_post' %}">+</a></div>
            {% endif %}
        </div>
        <!--SearchBox Section-->
                <form action="{% url 'search_result' %}" role="form" method="GET">
                <div class="search-box">
                    <div>
                        <select name="search-box" id="">
                            <option value="Everything">Everything</option>
                            <option value="Titles">Titles</option>
                            <option value="Descriptions">Descriptions</option>
                        </select>
                        <input type="text" name="q" placeholder="search ...">
                        <button type="submit" name="search"><i class="fa fa-search"></i></button>
                    </div>
                </div>
                </form>
    </header>
    {% if messages %}
        {% for message in messages %}
            <div style="background-color:#fff;color:#000;font-weight:bolder;padding:20px;width:100%;"> {{message}} </div>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock content %}
    <div style="margin-bottom: 150px;"></div>
    <footer>
        <span>&copy;  Elwil Reyes Hernandez | All Rights Reserved</span>
    </footer>
    <script src="{% static 'main.js' %}"></script>
</body>
</html>

templates/create_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<h1 style="text-align:center; margin-block:50px; color:red;">Hey {{user}}, Write something</h1>

<form method="POST" class="form-container">
    {% csrf_token %}    
    <div class="form-group">
        <label for="id_title" class="label">Title:</label>
        <input type="text" name="title" maxlength="400" required id="id_title" class="input-field">
    </div>
    <div class="form-group">
        <label for="id_content" class="label">Content:</label>
        <textarea class="tinymce input-field" cols="40" data-mce-conf="{"theme": "silver", "height": 500, "menubar": false, "browser_spellcheck": true, "plugins": "advlist,autolink,lists,link,image,charmap,preview,anchor,searchreplace,visualblocks,code,fullscreen,insertdatetime,media,table,help,wordcount", "toolbar": "undo redo | blocks | bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help", "directionality": "ltr", "strict_loading_mode": 1, "selector": "#id_content"}" id="id_content" name="content" rows="10"></textarea>
    </div>
    <div class="form-group">
        <label for="id_categories" class="label">Categories:</label>
        <select name="categories" required id="id_categories" class="input-field" multiple>
            <option value="4">Bugs and Glitches</option>
            <option value="5">Reviews</option>
            <option value="6">Betas and Suggestions</option>
            <option value="7">Top</option>
        </select>
    </div>
    <div class="form-group">
        <label for="id_tags" class="label">Tags:</label>
        <div class="helptext" id="id_tags_helptext">A comma-separated list of tags.</div>
        <input type="text" name="tags" required aria-describedby="id_tags_helptext" id="id_tags" class="input-field">
    </div>
    <input type="submit" value="Save" class="submit-btn">
</form>

{% endblock content %}

templates/detail.html
{% extends 'base.html' %}
{% load hitcount_tags %}
{% block content %}

    <div class="container">
        <!--Navigation-->
        <div class="navigate">
            <span><a href="{% url 'home' %}">MyForum - Forums</a> >> <a href="{{post.categories.all.0.get_url}}">{{post.categories.all.0}}</a> >> <a href="{{post.get_url}}">{{post.title}}</a></span>
        </div>

        <!--Topic Section-->
        <div class="topic-container">
            <!--Original thread-->
            <div class="head">
                <div class="authors">Author</div>
                <div class="content">Topic: {{post.title}} (Read {% get_hit_count for post %} Times)</div>
            </div>

            <div class="body">
                <div class="authors">
                    <div class="username"><a href="">{{post.user.fullname|title}}</a></div>
                    <div>Role</div>
                    <img src="{{post.user.profile_pic.url}}" alt="">
                    <div>Posts: <u>{{post.user.num_posts}}</u></div>
                    <div>Points: <u>{{post.user.points}}</u></div>
                </div>
                <div class="content">
                    {{post.content|safe}}
                    <br>
                    <div class="comment">
                        <button onclick="showComment()">Comment</button>
                    </div>
                </div>
            </div>
        </div>


        <!--Comment Area-->
        {% if post.closed == True %}
        <div style="background-color:#fff;color:#000;font-weight:bolder;padding:20px;width:100%;"> This Topic Is Closed! </div>
        {% else %}
        {% if request.user.is_authenticated %}
        <form action="." method="post">
            {% csrf_token %}
            <div class="comment-area hide" id="comment-area">
                <textarea name="comment" id="" placeholder="comment here ... "></textarea>
                <input type="submit" value="submit" name="comment-form">
            </div>
        </form>
        {% else %}
<div style="background-color:#fff;color:#000;font-weight:bolder;padding:20px;width:100%;"> You need to <a href="{% url 'signin' %}"><b>login</b></a> to comment or reply.! </div>        

        {% endif %}

        {% endif %}

        <!--Comments Section-->

        {% for comment in post.comments.all %}
        <div class="comments-container">
            <div class="body">
                <div class="authors">
                    <div class="username"><a href="">{{comment.user.fullname|title}}</a></div>
                    <div>Role</div>
                    <img src="{{comment.user.profile_pic.url}}" alt="">
                    <div>Posts: <u>{{comment.user.num_posts}}</u></div>
                    <div>Points: <u>{{comment.user.points}}</u></div>
                </div>
                <div class="content">
                    {{comment.content}}
                    <br>
                    {% if request.user.is_authenticted %}
                    <div class="comment">
                        <button onclick="showReplies('comment{{comment.id}}')">Reply</button>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <!--Reply Area-->
        <form action="." method="post">
            {% csrf_token %}
            <div class="comment-area hide" id="comment{{comment.id}}">
                <textarea name="reply" id="" placeholder="reply here ... "></textarea>
                <input type="submit" value="submit" name="reply-form">
                <input type="hidden" name="comment-id" value="{{comment.id}}">
            </div>
        </form>
       
        <!--Reply section-->
        {% for reply in comment.replies.all %}
        <div class="comments-container" style="width: 95%; margin-left:5%;">
            <div class="body">
                <div class="authors">
                    <div class="username"><a href="">{{reply.user.fullname|title}}</a></div>
                    <div>Role</div>
                    <img src="{{reply.user.profile_pic.url}}" alt="">
                    <div>Posts: <u>{{reply.user.num_posts}}</u></div>
                    <div>Points: <u>{{reply.user.points}}</u></div>
                </div>
                <div class="content">
                    {{reply.content}}
                    <br>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endfor %}

       
        

    </div>
    {% endblock content %}

templates/forums.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="subforum">
            {% if forums %}
                <div class="subforum-title">
                    <h1>General Information</h1>
                </div>

                {% for forum in forums %}
                    <div class="subforum-row">
                        <div class="subforum-icon subforum-column center">
                            <i class="fa fa-gamepad"></i>
                        </div>
                        <div class="subforum-description subforum-column">
                            <h4><a href="{{forum.get_url}}">{{forum.title}}</a></h4>
                            <p>Description: {{forum.description}} </p>
                        </div>
                        <div class="subforum-stats subforum-column center">
                            <span>{{forum.num_posts}} Posts</span>
                        </div>
                        <div class="subforum-info subforum-column">
                            {% if forum.last_post %}
                                <b><a href="{{forum.last_post.get_url}}">Last post</a></b> by <a href="">{{forum.last_post.user.fullname|title}}</a> 
                                <br>on <small>{{forum.last_post.date|date}}</small>
                            {% else %}
                                <span>No posts in this category.</span>
                            {% endif %}
                        </div>
                    </div>

                {% endfor %}
            {% else %}
                <div class="subforum-title">
                    <h1><i class="fa fa-frown-o"></i>&nbsp;you have no posts yet.</h1>
                </div>
            {% endif %}
        </div>
        <!--More-->
        
        
        
    </div>

    <!-- Forum Info -->
    <div class="forum-info">
        <div class="chart">
            MyForum - Stats &nbsp;<i class="fa fa-bar-chart"></i>
        </div>
        <span><u>{{num_posts}}</u> Posts in <u>{{num_categories}}</u> Categories by <u>{{num_users}}</u> Members.</span><br>
        {% if forums %}
            <span>Latest post: <b><a href="{{last_post.get_url}}">{{last_post.title}}</a></b> on {{last_post.date|date}} By <a href="">{{last_post.user.fullname|title}}</a></span>.<br>
            <span>Check <a href="{% url 'latest_posts' %}">the latest posts</a> .</span><br>
        {% endif %}
    </div>

    {% endblock content %}

templates/home.html
<h1>Selmi Abderrahim Says Hi ;)

templates/latest-posts.html
{% extends 'base.html' %}
{% load hitcount_tags %}
{% block content %}
    <div class="container">
        <!--Navigation-->
        <div class="navigate">
            <span>Latest 10 Posts</span>
        </div>
        <!--Display posts table-->
        <div class="posts-table">
            <div class="table-head">
                <div class="status">Status</div>
                <div class="subjects">Subjects</div>
                <div class="replies">Replies/Views</div>
                <div class="last-reply">Last Reply</div>
            </div>

            {% for post in posts %}
            <div class="table-row">
                <div class="status"><i class="fa fa-fire"></i></div>
                <div class="subjects">
                    <a href="{{post.get_url}}">{{post.title}}</a>
                    <br>
                    <span>Started by <b><a href="">{{post.user.fullname|title}}</a></b> .</span>
                </div>
                <div class="replies">
                    {{post.num_comments}} comments <br> {% get_hit_count for post %} views
                </div>

                <div class="last-reply">
                    {{post.last_reply.date|date}}
                    <br>By <b><a href="">{{post.last_reply.user.fullname|title}}</a></b>
                </div>
            </div>
            {% endfor %}

            
            
        </div>

    {% endblock content %}

templates/posts.html
{% extends 'base.html' %}
{% load hitcount_tags %}
{% block content %}
    <div class="container">
        <!--Navigation-->
        <div class="navigate">
            <span><a href="{% url 'home' %}">MyForum - Forums</a> >> <a href="{{forum.get_url}}">{{forum.title}}</a></span>
        </div>
        {% if posts %}
            <!--Display posts table-->
            <div class="posts-table">
                <div class="table-head">
                    <div class="status">Status</div>
                    <div class="subjects">Subjects</div>
                    <div class="replies">Replies/Views</div>
                    <div class="last-reply">Last Reply</div>
                </div>

                {% for post in posts %}
                <div class="table-row">

                    {% if post.closed == True %}
                    <div class="status"><i class="fa fa-lock"></i></div>
                    {% elif post.num_comments == 0 %}
                    <div class="status"><i class="fa fa-frown-o"></i></div>
                    {% elif post.num_comments > 0 and post.num_comments < 2 %}
                    <div class="status"><i class="fa fa-book"></i></div>
                    {% elif post.num_comments > 2 and post.num_comments < 4 %}
                    <div class="status"><i class="fa fa-rocket"></i></div>
                    {% elif post.num_comments >= 4 %}
                    <div class="status"><i class="fa fa-fire"></i></div>
                    
                    {% endif %}


                    <div class="subjects">
                        <a href="{{post.get_url}}">{{post.title}}</a>
                        <br>
                        <span>Started by <b><a href="">{{post.user.fullname|title}}</a></b> .</span>
                    </div>
                    <div class="replies">
                        {{post.num_comments}} comments <br> {% get_hit_count for post %} views
                    </div>

                    {% if post.last_reply %}
                    <div class="last-reply">
                        {{post.last_reply.date|date}}
                        <br>By <b><a href="">{{post.last_reply.user.fullname|title}}</a></b>
                    </div>
                    {% else %}
                    <div class="last-reply">
                        {{post.date|date}}
                        <br>By <b><a href="">{{post.user.fullname|title}}</a></b>
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
            {% else %}
            <div class="subforum-title">
                <h1><i class="fa fa-frown-o"></i>&nbsp;you have no posts yet.</h1>
            </div>
            {% endif %}
            
            
        </div>
        <!--Pagination starts-->
            {% if posts.is_paginated %}
                <div class="pagination">
                    pages: {% for num_page in posts.paginator.page_range %} <a href="?page={{num_page}}">{{num_page}}</a> {% endfor %}
                </div>
            {% endif %}
        <!--pagination ends-->
    </div>

    <!-- <div class="note">
        <span><i class="fa fa-frown-o"></i>&nbsp; 0 Engagement Topic</span>&nbsp;&nbsp;&nbsp;<a href=""><i class="fa fa-share-square"></i></a><br>
        <span><i class="fa fa-book"></i>&nbsp; Low Engagement Topic</span>&nbsp;&nbsp;&nbsp;<a href=""><i class="fa fa-share-square"></i></a><br>
        <span><i class="fa fa-fire"></i>&nbsp; Popular Topic</span>&nbsp;&nbsp;&nbsp;<a href=""><i class="fa fa-share-square"></i></a><br>
        <span><i class="fa fa-rocket"></i>&nbsp; High Engagement Topic</span>&nbsp;&nbsp;&nbsp;<a href=""><i class="fa fa-share-square"></i></a><br>
        <span><i class="fa fa-lock"></i>&nbsp; Closed Topic</span>&nbsp;&nbsp;&nbsp;<a href=""><i class="fa fa-share-square"></i></a><br>
    </div> -->
    {% endblock content %}

templates/search.html
{% extends 'base.html' %}
{% load hitcount_tags %}
{% block content %}
    <div class="container">
        <!--Navigation-->
        <div class="navigate">
            <span>Search: {{query}} --> {{objects|length}} Result(s) Found</span>
        </div>
        <!--Display posts table-->
        <div class="posts-table">
            <div class="table-head">
                <div class="status">Status</div>
                <div class="subjects">Subjects</div>
                <div class="replies">Replies/Views</div>
                <div class="last-reply">Last Reply</div>
            </div>

            {% for post in objects %}
            <div class="table-row">
                <div class="status"><i class="fa fa-fire"></i></div>
                <div class="subjects">
                    <a href="{{post.get_url}}">{{post.title}}</a>
                    <br>
                    <span>Started by <b><a href="">{{post.user.fullname|title}}</a></b> .</span>
                </div>
                <div class="replies">
                    {{post.num_comments}} comments <br> {% get_hit_count for post %} views
                </div>

                {% if post.last_reply %}
                <div class="last-reply">
                    {{post.last_reply.date|date}}
                    <br>By <b><a href="">{{post.last_reply.user.fullname|title}}</a></b>
                </div>
                {% else %}
                <div class="last-reply">
                    {{post.date|date}}
                    <br>By <b><a href="">{{post.user.fullname|title}}</a></b>
                </div>
                {% endif %}
            </div>
            {% endfor %}

            
            
        </div>
        <!--Pagination starts-->
            {% if objects.is_paginated %}
            <div class="pagination">
                pages: {% for num_page in posts.paginator.page_range %} <a href="?page={{num_page}}">{{num_page}}</a> {% endfor %}
            </div>
            {% endif %}
        <!--pagination ends-->
    </div>

    {% endblock content %}